version: "3.0"

services:

  qestbot_ros2:
    image: manojm003/questbot:latest
    container_name: 'questbot_ros2_container'
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=5
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    network_mode: host
    working_dir: '/home/questbot/'
    tty: true