name: Docker Image CI

on:
  push:
    branches:
    - main
    paths:
    - .github/docker/Dockerfile
  pull_request:
    branches:
    - main
    paths:
    - .github/docker/Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Build the Docker image
        run: docker build . --file ./.github/docker/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:latest
